services:
  notice_service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_USER=root
      - DB_PASSWORD=P*ssW0rd
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=notice_db
    depends_on:
      - mysql
    ports:
      - "5004:5004"
    networks:
      - app-network
        
  mysql:
    image: kyk000306/test-mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: P*ssW0rd
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge