version: '3.8'

services:
  login_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5006:5006"
    depends_on:
      - mysql
    env_file:
      - ./.env

  mysql:
    image: kyk000306/test-mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: P*ssW0rd
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
