apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: main-service-rbac
rules:
  - apiGroups: ["autoscaling/v2"]
    resources: ["horizontalpodautoscalers", "nodes/metrics", "pods", "nodes"]
    verbs:
      - create
      - get
      - list
      - update
      - delete
      - watch
  - apiGroups: [""]
    resources: ["pods"]
    verbs:
      - get
      - list
      - watch