apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-service-container
spec:
  replicas: 5
  selector:
    matchLabels:
      app: login-service
  template:
    metadata:
      labels:
        app: login-service
    spec:
      containers:
        - name: login-service-container
          image: ghcr.io/yeongkyukang/login_service:latest # 기본값 설정
      imagePullSecrets:
        - name: ghcr-secret