apiVersion: v1
kind: Service
metadata:
  name: festival-service-svc
  labels:
    app: festival-service
  namespace: default
spec:
  selector:
    app: festival-service
  ports:
    - protocol: TCP
      port: 80         
      targetPort: 5002
    - protocol: TCP
      port: 443
      targetPort: 5001
  type: LoadBalancer